### ISSUE TITLE
How to I can pass sv_setsteamaccount parameter?

### ISSUE THREAD

**Issue by torquemada163** [joshhsoj1902/linuxgsm-docker#153]
Hello!

I need use parameter **sv_setsteamaccount <<token>>** in container. How I can do this?

**Comment by joshhsoj1902** [comment]
Which game are you looking to set that value for?

If the setting is something that can be simply put in the LGSM "_default.cfg" ([see here](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/cssserver/_default.cfg))

You can set the value by setting the environment variable `LGSM_SV_SETSTEAMACCOUNT` and the value should be injected.

If instead the value needs to be put into game specific config ([see here](https://github.com/GameServerManagers/Game-Server-Configs/blob/master/CounterStrikeGlobalOffensive/server.cfg)) , I would need to throw together a template file for it. The templates are fairly simple to create, I just have to keep them in sync manually so I've been adding new ones as needed. 

The other game configs I already have are in this folder: https://github.com/joshhsoj1902/linuxgsm-docker/tree/master/config-game-template

I can throw together a template this evening
